<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="<?= $this->Config('dominio') ?>" title="<?= $this->Config('slogan') ?>" style="padding-top: 0px;">
        <img src="/assets/img/logo/logo-menu.png" />
    </a>
</div>
<?php if ($this->Auth()) { ?>

    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/mcnetwork-index/index" style="cursor: default">
                <?= ucwords($this->Auth()->nm_usuario); ?>    
            </a>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  
                <i class="fa fa-caret-down"></i>
            </a>            
            <ul class="dropdown-menu dropdown-user">
                <!--            
                <li>
                    <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <!--<li class="divider"></li>
                -->
                <li class="dropdown">
                    <a href="<?= $this->url('logoff') ?>">
                        <i class="glyphicon glyphicon-log-out"></i> Sair
                    </a>
                </li>
            </ul>
        </li>  
    </ul>

    <?= $this->render('layout/' . $this->Config('tema') . '/menu') ?>                    

<?php } else { ?>


<?php } ?>
