<?php
  /** @var $form \Endereco\Form\Endereco */
  /** @var $lista \Endereco\Service\Endereco[] */
?>
<div class="page-head">
    <h2>Lista</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>">Novo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Logradouro</th> 
                                <th>Número</th> 
                                <th>Complemento</th> 
                                <th>Bairro</th> 
                                <th>Cep</th> 
                                
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($lista as $item){ ?>
                            <tr>
                                <td><?=$item->getNmLogradouro()?></td> 
                                <td><?=$item->getNrNumero()?></td> 
                                <td><?=$item->getNmComplemento()?></td> 
                                <td><?=$item->getNmBairro()?></td> 
                                <td><?=$item->getNrCep()?></td> 
                                                                
                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>    
</div>
