<div class="page-head">
    <h2>Bem vindo ao Sistema</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">
                    <?php
                    $form->setAttribute('action', $this->url('navegacao', array('controller'=>'event','action' => 'gravar')));
                    $form->setAttribute('class', 'form-horizontal');
                    $form->setAttribute('data-role', 'form');
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('Code'));
                    ?>
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('Titulo')); ?>
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('Descricao')); ?>
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('Urgencia')); ?>
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-10">
                            <button type="submit" class="btn btn-default">Salvar</button>
                        </div>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
