<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css" >           
<br />
<div class="col-xs-12 content">
    <div class="well">
        <?php
        $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('data-toggle', 'validator');
        $form->prepare();
        echo $this->form()->openTag($form);
        $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($idUsuario));
        echo $this->formHidden($form->get('id'));
        ?>
        <div class="form-group">
            <div class="col-md-7">
                <?= $this->formRow($form->get('nm_usuario')) ?>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-7">
                <?= $this->formRow($form->get('em_email')) ?>
                <div class="help-block with-errors"></div>
            </div>                    
        </div>
        <div class="form-group">
            <div class="col-md-7">
                <?= $this->formRow($form->get('nu_cpf')) ?>
                <div class="help-block with-errors"></div>
            </div>                    
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<script src="/assets/compact-js/validator.min.js,jquery.mask.min.js,mc-network|relatorio|dados-pessoais.js" type="text/javascript"></script>
