<div class="list-group-item">
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseRelatorio1" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Relatório de Pagamentos Recebidos
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseRelatorio2" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Relatório de Bônus Pagos
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseRelatorio3" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Relatório de Saques Pagos
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseRelatorio4" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Relatório de Cadastrados
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseRelatorio6" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Relatório de Saldo dos Usuários
                    </h4>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório de Pagamentos Recebidos</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-1"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-2">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório de Bônus Pagos</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-2"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-3">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório de Saques Pagos</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-3"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-4">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório de Cadastrados</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-4"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-5">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório Unilevel</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-5"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-6">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Relatório de Saldo dos Usuários</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-6"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-7">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Dados do Usuário para Emissão de Nota</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-7"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn-nota-emitida">Nota Emitida!</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-relatorio-8">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Editar usuário</h4>
            </div>
            <div class="modal-body" id="modal-relatorio-body-8"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn-salvar-edicao-usuario">Salvar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div id="printSection"</div>

<script src="/assets/compact-js/mc-network|relatorio|index.js" type="text/javascript"></script>    