<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css,bootstrap-datetimepicker.min.css,mc-network|rede|list.css">
<div class="row">
    <div class="col-md-12 ">
        <div class="form-inline">
            <div class="col-md-12">
                <div class="btn-toolbar">                    
                    <div class="btn-group pull-right">                                            
                        <button type="button" class="btn btn-default" id="imprimirRelatorioUnilevel"
                                title="Imprimir">
                            <span class="glyphicon glyphicon-print"></span> Imprimir
                        </button>                        
                    </div>
                </div>
            </div>                
        </div> 
        <div class="table-responsive">
            <div class="row">
                <div class="col-md-9">
                    <table>
                        <tbody>
                            <tr>
                                <th colspan="1" class="file">
                                    <span title="" data-content="">
                                        <img src="/assets/img/user_ativo_pq.png">
                                    </span>
                                </th>            
                            </tr>
                            <tr>
                                <th class="empty">
                        <table>
                            <tbody>
                                <?php
                                $qtd1 = count($list1);
                                $count1 = 0;

                                foreach ($list1 as $contrato1) {

                                    $count1++;

                                    if ($qtd1 >= $configList['qtd_por_nivel']) {

                                        if ($qtd1 == $count1) {

                                            $class1 = 'end';
                                            $class10 = 'empty';
                                        } else {

                                            $class1 = 'start';
                                            $class10 = 'fill';
                                        }
                                    } else {

                                        $class1 = 'start';
                                        $class10 = 'fill';
                                    }

                                    $dateAdesao = new \DateTime($contrato1['dt_adesao']);
                                    ?>
                                    <tr>
                                        <th colspan="1" class="<?= $class1 ?>">
                                            <span
                                                id="popover_<?= $contrato1['id_contratos_as_contratos']; ?>"   
                                                data-toggle="popover"
                                                title='<?= \Estrutura\Helpers\String::nomeMaiusculo($contrato1['nm_usuario']) . ' - "' . Estrutura\Helpers\Cript::encCod($contrato1['id_usuario']) . '"'; ?>' 
                                                data-content="<?=
                                                '<p>Nível: ' . $contrato1['id_nivel'] . '</p>'
                                                . '<p>Situação: ' . $contrato1['nm_situacao_usuario'] . '</p>'
                                                . '<p>Email: ' . $contrato1['em_email'] . '</p>'
                                                . '<p>Telefone: ' . \Estrutura\Helpers\Telefone::telefoneMask($contrato1['nr_ddd_telefone'] . $contrato1['nr_telefone']) . '</p>'
                                                . '<p>Data de adesão: ' . $dateAdesao->format('d/m/Y') . '</p>'
                                                ?>">
                                                    <?php
                                                    if ($contrato1['id_situacao_usuario'] == $configList['situacao_usuario_ativo']) {
                                                        ?>
                                                    <img src="/assets/img/user_ativo_pq.png" style="cursor: pointer;">
                                                    <?php
                                                } else {
                                                    ?>
                                                    <img src="/assets/img/user_inativo_pq.png" style="cursor: pointer;">
                                                    <?php
                                                }
                                                ?>
                                            </span>
                                        </th>
                                    </tr>                        
                                    <?php
                                    $qtd2 = count($list2);

                                    $count2 = 0;
//                    if ($qtd2 > 0) {

                                    $possuiFilho2 = 0;
                                    foreach ($list2 as $contrato2) {

                                        if ($contrato2['id_contrato_indicacao'] == $contrato1['id_contrato_filho']) {

                                            $possuiFilho2++;
//                                break;
                                        }
                                    }
                                    ?>
                                    <tr> 
                                        <th class="<?= $class10 ?>" style="display: none;">
                                <table>
                                    <tbody>
                                        <?php
                                        if ($possuiFilho2) {
                                            foreach ($list2 as $contrato2) {

                                                if ($contrato2['id_contrato_indicacao'] == $contrato1['id_contrato_filho']) {

                                                    $count2++;

                                                    //                                            if ($configList['qtd_por_nivel'] == $count2) {
                                                    if ($possuiFilho2 >= $configList['qtd_por_nivel']) {

                                                        if ($possuiFilho2 == $count2) {

                                                            $class2 = 'end';
                                                            $class20 = 'empty';
                                                        } else {

                                                            $class2 = 'start';
                                                            $class20 = 'fill';
                                                        }
                                                    } else {

                                                        $class2 = 'start';
                                                        $class20 = 'fill';
                                                    }

                                                    $dateAdesao = new \DateTime($contrato2['dt_adesao']);
                                                    ?>
                                                    <tr>
                                                        <th colspan="1" class="<?= $class2 ?>">
                                                            <span
                                                                data-toggle="popover"
                                                                title='<?= \Estrutura\Helpers\String::nomeMaiusculo($contrato2['nm_usuario']) . ' - "' . Estrutura\Helpers\Cript::encCod($contrato2['id_usuario']) . '"'; ?>' 
                                                                data-content="<?=
                                                                '<p>Nível: ' . $contrato2['id_nivel'] . "</p>"
                                                                . '<p>Situação: ' . $contrato2['nm_situacao_usuario'] . '</p>'
                                                                . '<p>Email: ' . $contrato2['em_email'] . '</p>'
                                                                . '<p>Telefone: ' . \Estrutura\Helpers\Telefone::telefoneMask($contrato2['nr_ddd_telefone'] . $contrato2['nr_telefone']) . '</p>'
                                                                . '<p>Data de adesão: ' . $dateAdesao->format('d/m/Y') . '</p>';
                                                                ?>">
                                                                    <?php
                                                                    if ($contrato2['id_situacao_usuario'] == $configList['situacao_usuario_ativo']) {
                                                                        ?>
                                                                    <img src="/assets/img/user_ativo_pq.png" style="cursor: pointer;">
                                                                    <?php
                                                                } else {
                                                                    ?>
                                                                    <img src="/assets/img/user_inativo_pq.png" style="cursor: pointer;">
                                                                    <?php
                                                                }
                                                                ?>
                                                            </span>
                                                        </th>
                                                    </tr>     
                                                    <?php
                                                    $qtd3 = count($list3);
                                                    $count3 = 0;

//                                        if ($qtd3 > 0) {


                                                    $possuiFilho3 = 0;
                                                    foreach ($list3 as $contrato3) {

                                                        if ($contrato3['id_contrato_indicacao'] == $contrato2['id_contrato_filho']) {

                                                            $possuiFilho3++;
//                                                    break;
                                                        }
                                                    }
                                                    ?>
                                                    <tr>
                                                        <th class="<?= $class20; ?>" style="display: none;">
                                                <table>
                                                    <tbody>
                                                        <?php
                                                        if ($possuiFilho3) {
                                                            foreach ($list3 as $contrato3) {

                                                                if ($contrato3['id_contrato_indicacao'] == $contrato2['id_contrato_filho']) {

                                                                    $count3++;

                                                                    //                                                        if ($configList['qtd_por_nivel'] == $count3) {
                                                                    if ($possuiFilho3 >= $configList['qtd_por_nivel']) {

                                                                        if ($possuiFilho3 == $count3) {

                                                                            $class3 = 'end';
                                                                        } else {

                                                                            $class3 = 'start';
                                                                        }
                                                                    } else {

                                                                        $class3 = 'start';
                                                                    }

                                                                    $dateAdesao = new \DateTime($contrato3['dt_adesao']);
                                                                    ?>
                                                                    <tr>
                                                                        <th colspan="1" class="<?= $class3 ?>" title="<?= 'Nivel: ' . $contrato3['id_nivel'] . "-  contratos_as_contratos: " . $contrato3['id_contratos_as_contratos'] ?>" >
                                                                            <span
                                                                                data-toggle="popover"
                                                                                title='<?= \Estrutura\Helpers\String::nomeMaiusculo($contrato3['nm_usuario']) . ' - "' . Estrutura\Helpers\Cript::encCod($contrato3['id_usuario']) . '"'; ?>' 
                                                                                data-content="<?=
                                                                                '<p>Nível: ' . $contrato3['id_nivel'] . "</p>"
                                                                                . '<p>Situação: ' . $contrato3['nm_situacao_usuario'] . '</p>'
                                                                                . '<p>Email: ' . $contrato3['em_email'] . '</p>'
                                                                                . '<p>Telefone: ' . \Estrutura\Helpers\Telefone::telefoneMask($contrato3['nr_ddd_telefone'] . $contrato3['nr_telefone']) . '</p>'
                                                                                . '<p>Data de adesão: ' . $dateAdesao->format('d/m/Y') . '</p>';
                                                                                ?>">
                                                                                    <?php
                                                                                    if ($contrato3['id_situacao_usuario'] == $configList['situacao_usuario_ativo']) {
                                                                                        ?>
                                                                                    <img src="/assets/img/user_ativo_pq.png" style="cursor: pointer;">
                                                                                    <?php
                                                                                } else {
                                                                                    ?>
                                                                                    <img src="/assets/img/user_inativo_pq.png" style="cursor: pointer;">
                                                                                    <?php
                                                                                }
                                                                                ?>
                                                                            </span>
                                                                        </th>
                                                                    </tr>     
                                                                    <?php
                                                                }
                                                            }
                                                        }
                                                        for ($i3 = $count3; $i3 < $configList['qtd_por_nivel']; $i3++) {
                                                            ?>
                                                            <tr>
                                                                <th colspan="1" class="<?= $i3 == $configList['qtd_por_nivel'] - 1 ? 'end' : 'start' ?>">
                                                                    <img src="/assets/img/user_congelado_pq.png">
                                                                </th>
                                                            </tr>                             
                                                            <?php
                                                        }
                                                        ?>
                                                    </tbody>
                                                </table>                
                                                </th>
                                                </tr>
                                                <?php
//                                    }
                                            }
                                        }
                                    }
                                    for ($i2 = $count2; $i2 < $configList['qtd_por_nivel']; $i2++) {
                                        ?>
                                        <tr>
                                            <th colspan="1" class="<?= $i2 == ($configList['qtd_por_nivel'] - 1) ? 'end' : 'start' ?>">
                                                <img src="/assets/img/user_congelado_pq.png">
                                            </th>
                                        </tr>                             
                                        <?php
                                    }
                                    ?>
                                    </tbody>
                                </table>                
                                </th>
                                </tr>
                                <?php
//                }
                            }
                            for ($i1 = $count1; $i1 < $configList['qtd_por_nivel']; $i1++) {
                                ?>
                                <tr>
                                    <th colspan="1" class="<?= $i1 == $configList['qtd_por_nivel'] - 1 ? 'end' : 'start' ?>">
                                        <img src="/assets/img/user_congelado_pq.png">
                                    </th>
                                </tr>                             
                                <?php
                            }
                            ?>
                            </tbody>
                        </table>                
                        </th>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-3">
                    <br>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <img src="/assets/img/user_congelado_pq.png">
                            <p>Vazio</p>
                        </div>
                    </div>            
                    <br>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <img src="/assets/img/user_inativo_pq.png">
                            <p>Inativo</p>
                        </div>
                    </div>            
                    <br>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <img src="/assets/img/user_ativo_pq.png">
                            <p>Ativo</p>
                        </div>
                    </div>                        
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js,mc-network|relatorio|relatorio-unilevel.js" type="text/javascript"></script>    