<div class="list-group-item">
    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisao1" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 5% para quem indicou 1 pessoa
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisao2" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 10% para quem indicou 2 pessoas
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisao3" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 15% para quem indicou 3 pessoas
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisao4" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 20% para quem indicou 4 pessoas
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisao5" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 25% para quem indicou 5 pessoas
                    </h4>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading" id="collapseDivisaoMais5" style="cursor: pointer;">
                    <h4 class="panel-title">
                        Divisão de lucro de 25% para quem indicou mais de 5 pessoas
                    </h4>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 5% para quem indicou 1 pessoa</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-1"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-2">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 10% para quem indicou 2 pessoas</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-2"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-3">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 15% para quem indicou 3 pessoas</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-3"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-4">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 20% para quem indicou 4 pessoas</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-4"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-5">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 25% para quem indicou 5 pessoas</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-5"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade printable" id="modal-divisao-mais5">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                <h4 class="modal-title">Divisão de lucro de 25% para quem indicou mais de 5 pessoas</h4>
            </div>
            <div class="modal-body" id="modal-divisao-body-mais5"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>                
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-1-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-1">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-2">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-2-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-2">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-3">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-3-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-3">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-4">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-4-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-4">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-5">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-5-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-5">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-confirm-divisao-mais5">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Atenção: Essa operação não pode ser revertida</h4>
            </div>
            <div class="modal-body" id="modal-confirm-divisao-mais5-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" id="btn-ok-confirm-divisao-mais5">Pagar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-message-divisao">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span>
                </button>
                <h4 class="modal-title">Mensagem</h4>
            </div>
            <div class="modal-body" id="modal-message-divisao-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>                    
            </div>
        </div>
    </div>
</div>

<script src="/assets/compact-js/mc-network|divisao|index.js" type="text/javascript"></script>    