<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css,bootstrap-datetimepicker.min.css">

<div class="row">
    <div class="col-md-12 ">
        <div class="row">
            <div class="form-inline">
                <div class="col-md-4">
                    <div class="form-group datetimepicker">
                        <label for="dt_inicio">Início:</label>
                        <input type="text" name="dt_inicio" 
                               id="dt_inicio" 
                               class="form-control" 
                               data-mask="00/00/0000" 
                               data-date-format="DD/MM/YYYY" 
                               required="required" 
                               data-error="Campo é obrigatório." 
                               value="<?= $dtInicio ?>" 
                               maxlength="10" autocomplete="off">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group datetimepicker">
                        <label for="dt_fim">Fim:</label>
                        <input type="text" name="dt_fim" 
                               id="dt_fim" 
                               class="form-control" 
                               data-mask="00/00/0000" 
                               data-date-format="DD/MM/YYYY" 
                               required="required" 
                               data-error="Campo é obrigatório." 
                               value="<?= $dtFim ?>" 
                               maxlength="10" autocomplete="off">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="btn-toolbar">     
                        <div class="btn-group">      
                            <button type="button" class="btn btn-primary" id="filtrarRelatorioBonusPagos"
                                    title="Filtrar">
                                <span class="glyphicon glyphicon-search"></span> Filtrar
                            </button>                        
                            <button type="button" class="btn btn-default" id="limparRelatorioBonusPagos"
                                    title="Limpar" aria-label="Left Align">
                                <span class="glyphicon glyphicon glyphicon-repeat"></span> Limpar
                            </button>
                            <button type="button" class="btn btn-default" id="imprimirRelatorioBonusPagos"
                                    title="Imprimir">
                                <span class="glyphicon glyphicon-print"></span> Imprimir
                            </button>                       
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
        <br>
        <!--TABELA RESUMO GERAL-->
        <div class="table-responsive">
            <table class="table table-striped" id="tablesorterBonusPagos">
                <thead>
                    <tr>
                        <th class="text-center">Nº</th>
                        <th class="text-center" title="Referência">Ref.</th>
                        <th class="text-center">Mês</th>
                        <th class="text-center">Pagamento</th>
                        <th class="text-center">Valor</th>
                        <th class="text-center">Contrato</th>
                        <th class="text-center">Nome</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th class="text-center">Nº</th>
                        <th class="text-center" title="Referência">Ref.</th>
                        <th class="text-center">Mês</th>
                        <th class="text-center">Pagamento</th>
                        <th class="text-center">Valor</th>
                        <th class="text-center">Contrato</th>
                        <th class="text-center">Nome</th>
                    </tr>
                    <tr>
                        <th colspan="7" class="ts-pager form-horizontal">
                            <button type="button" class="btn first">
                                <i class="icon-step-backward glyphicon glyphicon-step-backward"></i>
                            </button>
                            <button type="button" class="btn prev">
                                <i class="icon-arrow-left glyphicon glyphicon-backward"></i>
                            </button>
                            <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
                            <button type="button" class="btn next">
                                <i class="icon-arrow-right glyphicon glyphicon-forward"></i>
                            </button>
                            <button type="button" class="btn last">
                                <i class="icon-step-forward glyphicon glyphicon-step-forward"></i>
                            </button>
                            <select class="pagesize input-mini" title="Selecione o número de linhas">
                                <option selected="selected" value="100">100</option>
                                <option value="200">200</option>
                                <option value="300">300</option>
                                <option value="400">400</option>
                            </select>
                            <select class="pagenum input-mini" title="Selecione o número da página"></select>
                        </th>
                    </tr>
                </tfoot>
                <?php
                $totalLinhas = 0;
                $valorTotal = 0;
                if (!empty($listBonusPagos)) {
                    ?>
                    <tbody class="">
                        <?php
                        foreach ($listBonusPagos as $key => $extrato) {

                            $dataReferencia = new \DateTime(date('Y-m-d', strtotime($extrato['dt_mes_referencia'])));
                            $dataPagamento = new \DateTime(date('Y-m-d', strtotime($extrato['dt_pagamento'])));
                            $totalLinhas++;
                            $valorTotal += $extrato['vl_pago'];
                            ?>
                            <tr>
                                <td class="text-center"><?= $totalLinhas ?></td>
                                <td class="text-center"><?= \Estrutura\Helpers\String::preencheEsquerda($extrato['id_pagamento'], 8, '0') ?></td>
                                <td class="text-center"><?= $dataReferencia->format('m/Y') ?></td>
                                <td class="text-center"><?= $dataPagamento->format('d/m/Y') ?></td>
                                <td class="text-center">R$ <?= \Estrutura\Helpers\Valor::reais($extrato['vl_pago']) ?></td>
                                <td class="text-center">"<?= \Estrutura\Helpers\Cript::encCod($extrato['id_contrato']) ?>"</td>
                                <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($extrato['nm_usuario']) ?></td>
                            </tr>                    
                            <?php
                        }
                        ?>
                    </tbody>
                    <?php
                }
                ?>
            </table>                    
        </div>
        <div class="row">
            <div class="col-md-4">
                Total de linhas no período: <b><?= $totalLinhas; ?></b>
            </div>
            <div class="col-md-4">
                Valor total no período: <b>R$ <?= \Estrutura\Helpers\Valor::reais($valorTotal); ?></b>
            </div>
            <div class="col-md-4">
                <b><?= date("d/m/Y H:i:m"); ?></b>   
            </div>
        </div>
    </div>
</div>
<script src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js,mc-network|relatorio|relatorio-bonus-pagos.js" type="text/javascript"></script>    
