<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css" >  
<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
    <?php
    $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('data-toggle', 'validator');
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
                <div class="form-group">
                    <div class="col-md-3">
                        <h6 class="text-danger">* = Campo obrigatório</h6>
                    </div>
                    <div class="col-md-4 text-right">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
    <?php
    $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue())); 
    echo $this->formHidden($form->get('id'));
    ?>
                
                    
                    <?php
                    if ($form->get('dt_adesao')->getValue()) {
                        $form->get('dt_adesao')->setValue((new \DateTime($form->get('dt_adesao')->getValue()))->format('d/m/Y'));
                    }
                    ?>
                    <div class="form-group">
                        <div class="col-md-7">
                            <?= $this->formLabel($form->get('dt_adesao')) ?>
                            <div class="input-group" id="datetimepicker">
                                <?= $this->formInput($form->get('dt_adesao')) ?>
                                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>                            
                            </div>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('vl_saldo'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('id_situacao'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div><div class="form-group">
                        <div class="col-md-7">
                            <?=$this->formRow($form->get('id_usuario'))?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                <div class="form-group">
                    <div class="col-md-7 text-right">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
    <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,contrato|contrato|cadastro.js" type="text/javascript"></script>
