<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterContrato" >
            <thead>
                <tr>
                    <th class='text-center'>Data de adesão</th> 
                                <th class='text-center'>Saldo</th> 
                                
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class='text-center'>Data de adesão</th> 
                                <th class='text-center'>Saldo</th> 
                                
                    <th class="text-center">Ações</th>
                </tr>
                <tr>
                    <th colspan="3" class="ts-pager form-horizontal">
                        <?php
                        echo $this->paginationControl(
                                $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/contrato/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#contrato-pagination',
                                ]
                        );
                        ?>  
                    </th>
                </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="">
                    <tr role="row" class="tablesorter-filter-row">
                        <?php
                        foreach ($camposFilter as $key => $campoFilter) {
                            ?>    
                            <td>
                                <?php
                                if (!is_null($campoFilter)) {
                                    ?>
                                    <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>" value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                    <?php
                                } else {
                                    ?>
                                    &nbsp;                                        
                                    <?php
                                }
                                ?>
                            </td>
                            <?php
                        }
                        ?>                            
                    </tr>
                    <?php
                    foreach ($paginator as $key => $pagina) {
                        ?>
                        <tr>
                            <td class="text-center"><?= $pagina['dt_adesao'] ? (new \DateTime($pagina['dt_adesao']))->format('d/m/Y') : null ?></td>
                                <td class="text-center"><?= $pagina['vl_saldo'] ? \Estrutura\Helpers\Valor::reais($pagina['vl_saldo']) : null ?></td>
                                <td class="text-center"><span class="btn-group contrato-acoes-group" style="width: 130px;"><?= \Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro', 'id' => Estrutura\Helpers\Cript::enc($pagina['id_contrato'])))) ?><?= \Estrutura\Service\HtmlHelper::botaoExcluirConfirm(Estrutura\Helpers\Cript::enc($pagina['id_contrato'])) ?></span></td>                            
                        </tr>                    
                        <?php
                    }
                    ?>
                </tbody>
                <?php
            }
            ?>
        </table>
    </div>
</div>
<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>    
<script type="text/javascript" language="javascript">
    $(function () {

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterContrato").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                        // set the uitheme widget to use the bootstrap theme class names
                        // this is no longer required, if theme is set
                        // ,uitheme : "bootstrap"

            },
            headers: {
                2: {sorter: false}
            }
        });

        $("#imprimirRelatorioSaquesPagos").click(function () {

            var modalPrint = $('.modalPrint');
            modalPrint.removeClass('modal');
            $('.form-inline').hide();
            $('#printSection').addClass('printSection');
            $('#printSection').html(modalPrint.html());
            window.print();
            modalPrint.addClass('modal');
            $('.form-inline').show();
            $('#printSection').removeClass('printSection');
            $('#printSection').html('');
        });

        $('.contrato-acoes-group .btn-excluir').off('click').on('click', function () {

            var id = $(this).attr('rel');
            $("#modal-contrato-excluir-id").val(id);
            $('#modal-contrato-excluir').modal('show');
        });

        $('#btn-contrato-excluir-confirm').off('click').on('click', function () {

            $('#modal-contrato-excluir').modal('hide');
            var id = $("#modal-contrato-excluir-id").val();
            window.location.href = '/contrato/excluir/' + id;
        });
    });
</script>