<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css" >           
<br />
<div class="col-md-12 content">
    <div class="well">
        <div class="row">
            <div class="col-md-12">
                <button type="button" class="btn btn-primary btn-salvar-comunicado">Salvar</button>
                <button type="button" class="btn btn-default btn-voltar-comunicado">Voltar</button>
            </div>
        </div>
        <br />
        <?php
        $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('data-toggle', 'validator');
        $form->prepare();
        echo $this->form()->openTag($form);
        $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
        echo $this->formHidden($form->get('id'));
        ?>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formRow($form->get('nm_titulo_comunicado')) ?>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formRow($form->get('tx_comunicado')) ?>

                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formLabel($form->get('dt_comunicado')) ?>
                <div class="input-group" id="datetimepicker1">
                    <?= $this->formInput($form->get('dt_comunicado')) ?>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>                            
                </div>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formLabel($form->get('dt_expiracao')) ?>
                <div class="input-group" id="datetimepicker2">
                    <?= $this->formInput($form->get('dt_expiracao')) ?>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>                            
                </div>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formRow($form->get('id_situacao')) ?>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <?= $this->formRow($form->get('id_tipo_comunicado')) ?>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <button type="button" class="btn btn-primary btn-salvar-comunicado">Salvar</button>
                <button type="button" class="btn btn-default btn-voltar-comunicado">Voltar</button>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<script src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,comunicado|comunicado|cadastro.js" type="text/javascript"></script>
