<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12 divPrint">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterAction" >
            <thead>
                <tr>
                    <th class='text-center'>Ação</th> 
                                
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th class='text-center'>Ação</th> 
                                
                    <th class="text-center">Ações</th>
                </tr>
                <tr>
                    <th colspan="2" class="ts-pager form-horizontal">
                        <?php
                        echo $this->paginationControl(
                                $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/action/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#action-pagination',
                                ]
                        );
                        ?>  
                    </th>
                </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="">
                    <tr role="row" class="tablesorter-filter-row">
                        <?php
                        foreach ($camposFilter as $key => $campoFilter) {
                            ?>    
                            <td>
                                <?php
                                if (!is_null($campoFilter)) {
                                    ?>
                                    <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>" value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                    <?php
                                } else {
                                    ?>
                                    &nbsp;                                        
                                    <?php
                                }
                                ?>
                            </td>
                            <?php
                        }
                        ?>                            
                    </tr>
                    <?php
                    foreach ($paginator as $key => $pagina) {
                        ?>
                        <tr>
                            <td class="text-center"><?= $pagina['nm_action']?></td>
                                <td class="text-center"><span class="btn-group action-acoes-group" style="width: 140px;"><?= \Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro', 'id' => Estrutura\Helpers\Cript::enc($pagina['id_action'])))) ?><?= \Estrutura\Service\HtmlHelper::botaoExcluirConfirm(Estrutura\Helpers\Cript::enc($pagina['id_action'])) ?></span></td>                            
                        </tr>                    
                        <?php
                    }
                    ?>
                </tbody>
                <?php
            }
            ?>
        </table>
    </div>
</div>
<div id="printSection"></div>
<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js,action|action|index-pagination.js" type="text/javascript"></script>