<!--<link rel="stylesheet" href="/assets/video-js/video-js.css">
<video id="<?= \Estrutura\Helpers\Cript::enc($curso->getId()); ?>" class="video-js vjs-default-skin" controls
       preload="auto" width="100%" height="304" poster="<?= utf8_decode($curso->getArImagem()); ?>">
    <source src="/mcnetwork-cursos/download-video-course/<?= \Estrutura\Helpers\Cript::enc($curso->getId()); ?>" type='video/mp4'>
</video>
<script src="/assets/video-js/video.js"></script>-->

<iframe src="https://player.vimeo.com/video/<?= $curso->getArVideo(); ?>" 
    width="100%" height="304" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>