<div class="panel panel-primary">
    <div class="panel-heading" 
         title="<?= $content['post_title'] ?>">
        <h4 class="panel-title">
            <b>
                <?= $content['post_title'] ?>
            </b> 
        </h4>
    </div>
    <div class="col-xs-12 col-sm-12">
        <?= $content['post_content'] ?>

        <br>
        <br>
        <div class="row">

            <div class="col-4 col-xs-4 text-center">
                <?php
                if ($prevContent) {
                    ?>
                    <button id="btn-prev-content" class="btn btn-primary" rel="<?= \Estrutura\Helpers\Cript::enc($idCurso . '_' . $prevContent) ?>">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Aula Anterior
                    </button>
                    <?php
                }
                ?>
            </div>
            <div class="col-4 col-xs-4 text-center">
                <?php
                switch ($content['post_type']) {
                    case 'unit':
                        if ($conclusionContent[$idUnit][$idContent]) {
                            ?>
                            <button class="btn btn-success" disabled="disabled">
                                <i class="glyphicon glyphicon-ok"></i>
                                concluído
                            </button>
                            <?php
                        } else {
                            ?>
                            <button id="btn-mark-completion" class="btn btn-primary" rel="<?= \Estrutura\Helpers\Cript::enc($idCurso . '_' . $idContent) ?>">
                                <i class="glyphicon glyphicon-ok"></i>
                                Marcar como concluída
                            </button>                
                            <?php
                        }
                        break;
                    case 'quiz':
                        ?>
                        <div class="col-4 col-xs-4 text-center">
                            <button id="btn-start-test" class="btn btn-primary" rel="<?= \Estrutura\Helpers\Cript::enc($idCurso . '_' . $idContent) ?>">
                                <i class="glyphicon glyphicon-pencil"></i>
                                <?= $conclusionContent[$idUnit][$idContent] ? 'Continuar' : 'Iniciar teste' ?>
                            </button>
                        </div>                
                        <?php
                        break;
                }
                ?>
            </div>
            <div class="col-4 col-xs-4 text-center">
                <?php
                if ($nextContent) {
                    ?>
                    <button id="btn-next-content" class="btn btn-primary" rel="<?= \Estrutura\Helpers\Cript::enc($idCurso . '_' . $nextContent) ?>">
                        <i class="glyphicon glyphicon-chevron-right"></i>
                        Próxima Aula 
                    </button>
                    <?php
                }
                ?>
            </div>

        </div>
        <br>
    </div>
</div>
<script>

    $(function () {

        if ($('#panel_unit_<?= $idUnit ?>').hasClass('panel-default')) {

            $('#panel_unit_<?= $idUnit ?>').find('.collapseCurriculumUnit').trigger('click');
        } else {
            
            
        }
    });
</script>
<script src="/assets/compact-js/mc-network|cursos|course-content.js" type="text/javascript"></script>


