<script src="/assets/compact-js/mc-network|cursos|list-content.js" type="text/javascript"></script>
<br />

<div class="col-xs-12 col-sm-12">

    <div class="panel-group" id="accordion">
        <?php
        if (!empty($curriculuns[$idUnit])) {
            foreach ($curriculuns[$idUnit] as $key => $curriculum) {
                ?>
                <div class="panel panel-default">
                    <div class="panel-heading collapseCurriculumTitle" 
                         value="<?= \Estrutura\Helpers\Cript::enc($idCurso . '_' . $curriculum['ID']) ?>" 
                         id="CollapsibleCurriculum<?= $key ?>" style="cursor: pointer;" title="<?= $curriculum['post_title'] ?>">
                        <h4 class="panel-title">
                            <b>
                                <?= $curriculum['post_title']; ?>
                                <?php
                                if ($conclusionContent[$idUnit][$curriculum['ID']]) {
                                    switch ($curriculum['post_type']) {
                                        case 'unit':
                                            ?>
                                            <span style = "color: #398439;">
                                                <span class = "glyphicon glyphicon-ok"></span>
                                            </span>
                                            <?php
                                            break;
                                        default:
                                            break;
                                    }
                                }
                                ?>
                            </b> 
                        </h4>
                    </div>
                </div>
                <?php
            }
        }
        ?>
    </div>
</div>
<div class="col-xs-12 col-sm-9">
</div>


