<div class="row">
    <div class="col-md-12">
        Deseja realmente liberar o saque no valor de R$ <?= \Estrutura\Helpers\Valor::reais($pagamento['vl_documento']) ?>?
        <!--    <div class="col-md-12">
                Código de pagamento: <?php //= $pagamento->getTxCodPagamento()  ?>
            </div>-->
    </div>
</div>
<!--<div class="row">
    <div class="col-md-12">
        <img src="/mcnetwork-cursos/download-img-pay/<?php //= $id;  ?>" class="img-thumbnail">
    </div>
</div>-->
