<link rel="stylesheet" type="text/css" href="/assets/css/selectize.bootstrap2.css" />
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
        <div class="well">
            <div class="page-head">
                <h2>Alterar senha financeira</h2>
            </div>

            <br>
            <div class="row">
                <div class="col-md-12">
                    Quando você efetua o cadastro, automaticamente <b>sua senha financeira é cadastrada igual sua senha de login,</b> porém você pode alterar para uma senha diferente, adquirindo assim mais segurança.
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    Para sua segurança, altere periodicamente sua senha.
                </div>
            </div>
            <br>

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => 'usuario-usuario', 'action' => 'salvar-redefinicao-senha-financeira')));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-toggle', 'validator');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <div class="col-md-6">
                    <?= $this->formRow($form->get('pw_senha_financeira')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                    <?= $this->formRow($form->get('pw_nova_senha')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                    <?= $this->formRow($form->get('pw_nova_senha_confirm')) ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">
                    <?= $this->formRow($form->get('captcha')); ?>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary">Redefinir senha</button>                        
                    <a href="<?= $this->url('navegacao', ['controller' => 'usuario-usuario', 'action' => 'atualizar-dados']) ?>" class="btn btn-default">Voltar</a>                    
                </div>
            </div>

            <?php
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
    <?=
    $this->partial('partials/menu-right', [
        'auth' => $auth,
        'contratoEntity' => $contratoEntity,
        'configList' => $configList,
        'meusGanhosList' => $meusGanhosList,
        'mensalidadeFoiPaga' => $mensalidadeFoiPaga,
        'comunicados' => $comunicados,
    ]);
    ?>
</div>
<script src="/assets/compact-js/validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|alterar-senha.js" type="text/javascript"></script>