
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">    

        <?php
        if ($temSaqueComReciboEnviado) {
            ?>
            <div class="bs-callout bs-callout-info">
                <span class="glyphicon glyphicon-exclamation-sign"></span>
                Quando você solicita um saque, não é possível realizar atualizações cadastrais até o final do processamento.
            </div>    
            <?php
        } else {
            ?>

            <div class = "well">
                <div class = "page-head">
                    <h2>Atualização de dados cadastrais</h2>
                </div>

                <dl>
                    <dt>Alterar senha de login:</dt>
                    <dd>
                        <a href="/usuario-usuario/alterar-senha">Click aqui para alterar sua senha de login</a>
                    </dd>
                </dl>

                <dl>
                    <dt>Alterar senha financeira:</dt>
                    <dd>
                        <a href="/usuario-usuario/alterar-senha-financeira">Click aqui para alterar sua senha financeira</a>
                    </dd>
                </dl>

                <dl>
                    <dt>Nome Completo:</dt>
                    <dd><?= \Estrutura\Helpers\String::nomeMaiusculo($usuario['nm_usuario']); ?>
                    </dd>
                </dl>        
                <?php
                $dateAdesao = new \DateTime($usuario['dt_nascimento']);
                ?>
                <dl>
                    <dt>Data de nascimento: </dt>
                    <dd><?= $dateAdesao->format('d/m/Y') ?></dd>
                </dl>
                <dl>
                    <dt>CPF: </dt>
                    <dd><?= \Estrutura\Helpers\Cpf::cpfMask($form->get('nu_cpf')->getValue()); ?></dd>
                </dl>
                <dl>
                    <dt>E-mail: </dt>
                    <dd><?= $form->get('em_email')->getValue(); ?></dd>
                </dl>
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar-atualizacao')));
                $form->setAttribute('method', 'post');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-toggle', 'validator');
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_sexo')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_nacionalidade')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_estado_civil')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_profissao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nu_rg')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_telefone')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <h4>Endereço</h4>
                <hr />

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_logradouro')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_numero')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_complemento')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nm_bairro')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_estado')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <input type="hidden" name="id_cidade_aux" id="id_cidade_aux" value="<?= $form->get('id_cidade')->getValue(); ?>" />
                <div id="div_id_cidade">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?= $this->formRow($form->get('id_cidade')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_cep')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <h4>Dados Bancários</h4>
                <hr />

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_banco')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_agencia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_conta')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_tipo_conta')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <hr />
                <div class="form-group">                    
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?= $this->url('navegacao', array('controller' => 'mcnetwork-index', 'action' => 'index')) ?>" class="btn btn-default">Voltar</a>                    
                    </div>
                </div>


                <?= $this->form()->closeTag(); ?>
            </div>
            <?php
        }
        ?>
    </div>
    <?=
    $this->partial('partials/menu-right', [
        'auth' => $auth,
        'contratoEntity' => $contratoEntity,
        'configList' => $configList,
        'meusGanhosList' => $meusGanhosList,
        'mensalidadeFoiPaga' => $mensalidadeFoiPaga,
        'comunicados' => $comunicados,
    ]);
    ?>

</div>
<script src="/assets/compact-js/validator.min.js,jquery.mask.min.js,usuario|usuario|atualizar-dados.js" type="text/javascript"></script>