<script src="/assets/compact-js/mc-network|index|index.js" type="text/javascript"></script>
<div class="row row-offcanvas row-offcanvas-right">

    <p class="pull-right visible-xs text-right">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"
                style="padding: 1px 15px; line-height: 2.5; margin: 0 15px;">
            Menu lateral
        </button>
    </p>

    <div class="col-xs-12 col-sm-9">


    </div>
</div>