<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">

        <div class="jumbotron">
            <h2>Contrato de Venda de Produtos</h2>
            <p class="text-justify">
                <span>DE UM LADO: M.C DE SA LIMA - EPP, CPNJ 08.988.565/0001-30 situada à Sia TR 05 LT 05 35 SALA 211 ED. IMPORT CENTER GUARA, autorizada a vender os produtos da marca MC NETWORK e tendo o total direito do uso comercial da marca, doravante denominada simplesmente MC NETWORK e de outro na qualidade de REVENDEDOR AMBULANTE AUTÔNOMO, a seguir designado como PROMOTOR, melhor qualificado(a) na proposta de revenda, constante no anverso, resolvem celebrar o presente INSTRUMENTO PARTICULAR DE CONTRATO DE REVENDA DE PRODUTOS DA MARCA MC NETWORK, que se regerá pelas normas estatuídas na legislação brasileira, e de acordo com as condições gerais, conforme segue:</span>
            </p>
        </div>
        <div class="row">
            <div class="col-6 col-sm-6 col-lg-6">                
                <p class="text-justify">
                    <span>O PROMOTOR, deverá filiar-se a MC NETWORK, mediante a oposição da assinatura no formulário de proposta de divulgação e venda no anverso deste contrato, e será submetido à aprovação do seu crédito.</span>
                </p>
                <p class="text-justify">
                    <span>Aprovado o crédito a que aduz o item anterior e efetuada a compra do produto (cursos on-line) pelo PROMOTOR fica ajustado o direito de revenda de produtos da marca MC NETWORK (curso on-line).</span>
                </p>
                <p class="text-justify">
                    <span>Neste ato, o PROMOTOR declara estar ciente de todas as regras do MANUAL DO NEGÓCIO MC NETWORK, obrigando-se a cumpri-las na integralidade, especialmente, com aquela que determina o pagamento da mensalidade do curso mensal para manter a renovação deste Contrato de revenda.</span>
                </p>
                <p class="text-justify">
                    <span>O presente contrato obriga as partes, seus herdeiros e sucessores.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR, observado o disposto neste contrato, tem ampla liberdade de conduzir suas atividades da forma que melhor lhe convier e, nesse sentido, poderá a seu exclusivo critério exercer outras atividades remuneradas ou não, com ou sem vínculo empregatício e, com total independência de horários, roteiros, ordens ou subordinações em razão da MC NETWORK.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR concorda que a assinatura deste contrato e a compra do produto (cursos on-line) são os requisitos necessários para tornar-se um PROMOTOR. Pelo presente contrato o PROMOTOR reconhece ter recebido a disponibilização dos cursos on-line.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR poderá revender livremente os produtos (cursos on-line) por ele adquiridos da MC NETWORK, sem qualquer delimitação de região. Os preços e condições são definido no sistema da MC NETWORK.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR não poderá, expor o conteúdo ou exibir o produto comprado pela mesma, comercializado do sistema MC NETWORK.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR, a seu livre critério, poderá adquirir produtos MC NETWORK a qualquer tempo, se tornando revendedor.</span>
                </p>
                <p class="text-justify">
                    <span>Os preços dos produtos da marca MC NETWORK, para revenda ao PROMOTOR, serão aqueles vigentes na data da requisição.</span>
                </p>
                <p class="text-justify">
                    <span>O pagamento dos produtos MC NETWORK comprados pelo PROMOTOR E CLIENTES será sempre a vista.</span>
                </p>
                <p class="text-justify">
                    <span>Fica expressamente vedado ao PROMOTOR assumir quaisquer compromissos ou obrigações em nome da MC NETWORK, sob pena das medidas judiciais cabíveis.</span>
                </p>
                <p class="text-justify">
                    <span>Compromete-se o PROMOTOR:</span>
                <div>A) Apresentar e revender os produtos comercializado pela MC NETWORK;</div>
                <div>b) Não reproduzir, não desenvolver ou criar e nem tão pouco permitir a reprodução, desenvolvimento ou criação por qualquer meio, de materiais impressos ou gravados com a marca MC NETWORK, bem como ficam proibidas, as fixações ou colocações de cartazes, banners e afins com o nome MC NETWORK em ruas, avenidas e praças de qualquer localidade do território nacional ou do exterior.</div>
                </p>
            </div>
            <div class="col-6 col-sm-6 col-lg-6">                
                <p class="text-justify">
                    <span>Fica estipulado que a MC NETWORK poderá a seu exclusivo critério suspender e/ ou rescindir de pleno direito o presente contrato, se o PROMOTOR cometer práticas que firam qualquer das cláusulas do presente contrato ou do Manual do Negócio MC NETWORK. </span>
                </p>
                <p class="text-justify">
                    <span>Este contrato não estabelece entre as partes, nenhuma forma de sociedade, associação, agência, consórcio ou responsabilidade solidária, devendo o PROMOTOR responder por quaisquer obrigações junto a terceiros, órgãos públicos, autarquias, etc.</span>
                </p>
                <p class="text-justify">
                    <span>As partes se comprometem a enviar, tão logo tenham conhecimento, uma a outra, comunicação escrita, sobre quaisquer acontecimentos que envolvam ou comprometam o cumprimento de qualquer uma das cláusulas deste Contrato. </span>
                </p>
                <p class="text-justify">
                    <span>Fica expressamente vedada a utilização das marcas, sinais de propaganda e demais elementos de propriedade da MC NETWORK pelo PROMOTOR, salvo com autorização expressa da MC NETWORK.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR autoriza durante a vigência deste contrato à MC NETWORK usar seu nome, fotografia, história pessoal e/ou qualquer fonte de referência para produção de materiais promocionais e de propaganda, desistindo de qualquer direito à remuneração pelo seu uso.</span>
                </p>
                <p class="text-justify">
                    <span>É em benefício mútuo do negócio do PROMOTOR, bem como da MC NETWORK e de seus demais Distribuidores Independentes, que há uma uniformidade nas normas, e, elas refletem a prática que melhor capacita o crescimento de todos esses negócios. Assim, o PROMOTOR concorda que a MC NETWORK pode alterar a qualquer tempo, as regras contidas nos Manuais do Negócio MC NETWORK, de Procedimentos Operacionais e de Treinamento, bem como no Sistema de Marketing, sendo que a única comunicação necessária para isso é a publicação de eventual alteração no site da MC NETWORK. A MC NETWORK observará um prazo de 30 dias para aplicar qualquer eventual alteração, a contar da data de publicação no site.</span>
                </p>
                <p class="text-justify">
                    <span>O PROMOTOR não poderá ceder ou transferir, total ou parcialmente, este contrato a terceiros, sem prévio consentimento da MC NETWORK. </span>
                </p>
                <p class="text-justify">
                    <span>As partes elegem o Foro da Comarca de Brasília, Distrito federal, para dirimir quaisquer dúvidas decorrentes do presente Contrato, renunciando a qualquer outro por mais privilegiados que seja.</span>
                </p>
            </div>
        </div>
    </div><!--/span-->
</div><!--/row-->




