<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">

        <div class="jumbotron">
            <h2>Declaração de Segurança</h2>
        </div>
        <div class="row">
            <div class="col-6 col-sm-6 col-lg-6">
                <p>A MC Network Cursos On-Line ("MC Network" ou "sistema") está empenhada em usar algumas das mais avançadas tecnologias para segurança de aplicações via web (na Internet) disponíveis atualmente, incluindo mecanismos que atendem a padrões razoáveis de cuidado considerando as possibilidades técnica e economicamente razoáveis da tecnologia aplicável à Internet, como o uso de firewall para proteção contra acessos indevidos. Quando um usuário acessa o sistema usando o Microsoft Internet Explorer, a tecnologia Secure Socket Layer (SSL) protege as informações do usuário usando autenticação do servidor e criptografia de dados. No entanto, o usuário reconhece que não se pode ter expectativa de segurança total na Internet com relação a invasão de websites e a outros atos ilícitos.</p>
            </div>
            <div class="col-6 col-sm-6 col-lg-6">
                <p>O MC Network Cursos On-Line fornece para cada usuário login e senha únicos, que devem ser informados a cada vez que o usuário acessa o sistema.</p>
                <p>Além disso, o sistema permite a implementação de criptografia no banco de dados, aumentando o nível de segurança das informações do usuário para prevenir o uso indevido ou revelação das mesmas para pessoas não autorizadas.</p>
            </div><!--/span-->
        </div><!--/row-->
    </div><!--/span-->
</div><!--/row-->




