<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">

        <div class="jumbotron">
            <h2>Termos de Utilização do Serviço</h2>
            <p class="text-justify">Ao utilizar o sistema MC Network Cursos On-Line ("MC Network" ou "sistema"), o Usuário, concorda e adere a todas as condições destes termos de Uso ("Termos"), tornando-se pessoalmente responsável por sua observância.</p>
        </div>
        <div class="row">
            <div class="col-6 col-sm-6 col-lg-6">
                <h3>Licença de uso do sistema</h3>
                <p class="text-justify">A MC Network concedeu, por meio de contrato específico, licença de utilização do sistema em favor do Usuário. Em nenhuma situação é permitida a transferência, empréstimo, sublicenciamento, aluguel, permuta, enfim, qualquer forma de cessão, sublicença ou comercialização do sistema.</p>
                <h3>Propriedade intelectual e reprodução</h3>
                <p class="text-justify">Cópia do Software e Conteúdo - É expressamente proibida a duplicação, cópia ou reprodução, no todo ou em parte, do sistema ou conteúdo ou de sua respectiva documentação técnica, bem como a simples tentativa de desvendar o código-objeto do sistema por mecanismos de engenharia reversa ou quaisquer outros. Os conteúdos dos cursos distribuídos inicialmente no sistema são de propriedade intelectual da MC Network, estendendo-se aos mesmos o previsto nesta cláusula e nas cláusulas "LICENÇA DE USO DO SISTEMA" e "PROTEÇÃO" destes Termos.</p>
                <p class="text-justify">Links para site de terceiros - Na MC Network Cursos On-Line existem links para outros sites de conteúdo que não estão sob o controle da MC Network. Nestes casos, a MC Network não se responsabiliza pela confiabilidade de qualquer dado, opinião, recomendação, ou práticas de sites de terceiros.</p>
                <p class="text-justify">Marcas e ícones de terceiros - A apresentação de marcas ou logo de padrões (CPE – Common Platform Enumeration e CCE – Common Configuration Enumeration) é usada apenas como referência de que o MC Network suporta os padrões definidos pelos criadores de tais padrões. Os ícones apresentados na MC Network constituem propriedade de famfamfam e seu uso está amparado por licença da <a href="http://www.creativecommons.org/" target="_blank">Creative Commons</a>.</p>
                <h3>Proteção</h3>
                <p class="text-justify">A MC Network desenvolveu e é detentora exclusiva dos direitos de autor e quaisquer outros direitos de propriedade intelectual sobre o sistema e sua documentação técnica. A licença de uso do sistema não implica em permissão para vender o sistema ou para de qualquer forma transmitir quaisquer direitos sobre o mesmo, e sim apenas na aquisição do direito de uso da do sistema acessado pelo Usuário, que somente poderá ser exercido durante a vigência da licença de uso. Em nenhuma hipótese, os avisos contidos no sistema referentes à propriedade intelectual poderão ser removidos ou modificados.</p>
                <h3>Garantia</h3>
                <p class="text-justify">A MC Network assegura as garantias previstas na licença de uso do sistema concedida ao Usuário.</p>
                <h3>Término da licença e interrupção de uso</h3>
                <p class="text-justify">A licença de uso vigorará a partir da data de sua assinatura até que seja cancelada por qualquer das partes - MC Network ou Usuário -, de acordo com os termos e condições estabelecidos na licença de uso.</p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-6">
                <h3>Responsabilidades da MC Network</h3>
                <p class="text-justify">As responsabilidades da MC Network em relação ao sistema e aos serviços de manutenção são exclusivamente as previstas na licença de uso.</p>
                <h3>Responsabilidades legais do Usuário</h3>
                <p class="text-justify">A violação da licença de uso e/ou destes Termos sujeitam o Usuário a todas as responsabilidades cíveis e criminais previstas na legislação aplicável. O desconhecimento das obrigações legais e/ou contratuais não isentará a parte infratora de tal responsabilização. A cooperação do Usuário na prevenção de infrações contratuais, ou na imediata informação à MC Network sobre sua ocorrência e tomada de medidas corretivas adequadas, será considerada fundamental para evitar responsabilidades por negligência ou omissão.</p>
                <h3>Informação Suficiente</h3>
                <p class="text-justify">O Usuário, em seu nome reconhece que o acesso eletrônico a estes Termos, previamente ao acesso ao sistema, será considerado como condição válida e eficaz para ciência e observância, para todos os fins e efeitos.</p>
                <h3>Condições Gerais</h3>
                <p class="text-justify">A licença de uso prevalecerá sobre o conteúdo destes Termos, em caso de quaisquer dúvidas ou conflitos. Estes Termos obrigam as partes e seus herdeiros ou sucessores a qualquer título. O Usuário não poderá ceder a terceiros seus direitos decorrentes destes Termos. Estes Termos são regidos pelas leis brasileiras. Fica eleito o foro central da comarca de Brasília, Distrito federal como o único competente para dirimir as questões decorrentes dos presentes Termos, com renúncia expressa a qualquer outro, por mais privilegiado que seja.</p>
                <h3>Isenção de Responsabilidade</h3>
                <p class="text-justify">A MC Network não será responsável por qualquer dano, perda ou responsabilidade de qualquer natureza decorrentes da utilização ou incapacidade de usar este sistema, ou os serviços, ou conteúdos fornecidos a partir e através dele. Além disso, a MC Network não garante que este sistema e outros documentos ou produtos aos quais este sistema faz referência funcionem sem interrupções, sejam precisos ou livres de erros ou omissões.</p>
                <p class="text-justify">A menos que expressamente especificado de outra forma em um acordo entre o Usuário e a MC Network, o sistema e todas as informações pertinentes a estes Termos são fornecidos "no estado", sem quaisquer garantias ou condições, expressas ou implícitas, incluindo mas sem limitação, garantias de qualidade satisfatória ou adequação a determinada finalidade.</p>
            </div><!--/span-->
        </div><!--/row-->
    </div><!--/span-->
</div><!--/row-->




